### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by shinybrar** [CHIMEFRB/workflow#11]
Add user authentication to the workflow systems. This will allow the users to access the correct organization and team spaces within the workflow systems.

```
  frb.chimenet.ca/auth/chimefrb --> This goes to the CHIME/FRB Authentication
  frb.chimenet.ca/auth/chimesps --> This goes to the CHIME/SPS Authentication
```

- [ ] Add user authentication to the workflow systems.
- [x] Add the yaml configuration parameters to the workspace.
  ```yaml
  
  auth:
    method: token | basic | oauth | cert | none
    provider: github | gitlab | bitbucket | ldap | ...

    orgs: [SOMETHING]
    teams: [ELSE] 
    
    # Basic
    basic:
      user: <username>
      password: <password>
  ```
  - [x] Add the `auth` parameter to the `workflow` section of the workspace.
  - [x] Allow for future expansion of the `auth` parameter to include other authentication providers.
  - [ ] For now support `oauth` with only `github` as the provider and `token`
  - [x] When `auth` is `none` or not specified in the workspace, the workflow system will not require authentication.
