### ISSUE TITLE
FIX: CLI Fixes

### ISSUE THREAD

**Issue by shinybrar** [CHIMEFRB/workflow#27]
- [x] Print with different color when deploying with schedules vs pipelines in the CLI
- [x] Split out `workflow pipelines` and `workflow schedule`
  - In `workflow pipeline ls` also add a created time and site field
- [x] Workflow pipeline ps <NAME> <ID> under a --details
- [x] Add the following functionality for `workflow pipeline ps <NAME> <ID>
```
id:
name:
deployments: ⚪️ | 🟢 | 🟠 | 🔴 | ✅ | 
steps:
  a: 🟢 
  b: 🟠 
  c: ✅ 
```
- [x] Add a `-q, --quiet` command to only print IDs.
