### ISSUE TITLE
[Feature] Deployment Configuration

### ISSUE THREAD

**Issue by shinybrar** [CHIMEFRB/workflow#59]
Add deployers configuration to definitions.workspace

```yaml
---
deployers:
  <site>:
    "docker":
       <custom1>:
       <custom2>:
       mounts: Derived from Docker Spec
       networks: Derived from Docker Spec
```

e.g.
```python
from docker import Mount

deployers:
  site:
    docker:
      volumes: List[Mount]
```

Things to do:
- Make sure <site> is a set of `sites` from the main config
- Derived mount spec from docker compose spec itself, rather than writing it.
