### ISSUE TITLE
[BUG] Configs Issue

### ISSUE THREAD

**Issue by shinybrar** [CHIMEFRB/workflow#66]
When deploying a config, e.g.

```yaml
version: "2"
name: workflow-dev-pipeline

defaults:
  user: developer
  site: local

deployments:
  - name: sm
    site: local
    image: chimefrb/workflow:latest
    sleep: 1
    resources:
      cores: 1
      ram: 2G
    replicas: 1

pipeline:
  runs_on: sm
  steps:
    - name: math
      stage: 1
      matrix:
        alpha: [1, 2, 3]
        beta: [1, 2, 3]
      work:
        site: chime
        function: workflow.examples.function.math
        parameters:
          a: ${{ matrix.alpha }}
          b: ${{ matrix.beta }}
```

The user should be prompted with a warning in CLI informing them,

- [ ] If the user provided deployments, but never performs a pipeline step on the deployment, ask for confirmation.
- [ ] If the user provided deployments, has multiple works, with some works not on the deployment, ask for confirmation.
