### ISSUE TITLE
[BUG] `execute` function parses all output using `ast.literal_eval`

### ISSUE THREAD

**Issue by odarotto** [CHIMEFRB/workflow#71]
When creating a pipeline config like: 

```yaml
version: "2"
name: files-test
defaults:
  user: "test"
  site: "local" # (1)
  tags: ["tag1"]

pipeline:
  steps:
    - name: create-file
      stage: 1
      work:
        command: ["touch", "test.py"]
    - name: write-file
      stage: 2
      work:
        command: ["echo", "import os > test.py"]
    - name: write-file-2
      stage: 3
      work:
        command: ["echo", "print(os.environ) >> test.py"]
    - name: run-file
      stage: 4
      work:
        command: ["python", "test.py"]
    - name: finish
      stage: 4
      work:
        command: ["echo", "Finished"]
```

Steps `write-file` and `write-file-2` will fail due to:

![image](https://github.com/CHIMEFRB/workflow/assets/40160237/fd0d6fae-9599-48ea-94fd-d8ea9a66f3f4)
