### ISSUE TITLE
[FIX] Execute command fix

### ISSUE THREAD

**Issue by odarotto** [CHIMEFRB/workflow#83]
When running pipelines steps like:

```yaml
    - name: use-results
      stage: 2
      reference:
        sum: ${{pipeline.use-function.work.results.sum}}
        product: ${{pipeline.use-function.work.results.product}}
      work:
        command: ["echo ${{reference.sum}} && echo ${{reference.product}}"]
```

Workflow gives error when executing the command
